### ISSUE TITLE
Support for Addons?

### ISSUE THREAD

**Issue by jaynford** [Tusky/KoDiscord#11]
First off, I love this script and it works great. I was just wondering if it would be possible to just display the name of whatever is playing in Kodi? Basically I want my addon content that I watch to also show up in addition to the TV Shows and Movies. Also, I am a graphic designer and would be more than willing to help out with some basic icons for TV, Movies & Add-Ons if you need it. Thanks!

**Comment by Tusky** [comment]
I think it should identify any addons now, tested with Youtube and Twitch addons, and seemed to work fine with those 👍 Reopen if still an issue.

But yes icons are pretty rough I can only code :) If you have the time and could provide better icons that would be great.

**Comment by jaynford** [comment]
It hasn't worked for me on anything but TV/Movies. And I'll do the icons
this weekend.

**Comment by Tusky** [comment]
Could you point me to the addon you want to use? If it sends data to the
webinterface it should be picked up. (basically it should have a label or a
title)

When I have some time, I'll make sure it works. I'm not that familiar with addons, I'm not using any, I just installed the Youtube and Twitch addons for this issue too.

**Comment by jaynford** [comment]
i have tried it with both Giant Bomb and just straight up Youtube. I am on
Kodi 18 Beta, if that has anything to do with it.

**Comment by Tusky** [comment]
Do you have the latest version installed?
![image](https://user-images.githubusercontent.com/1206970/45127630-89736380-b179-11e8-8369-1ac290a4a1c6.png)
Giant bomb seems to work perfectly fine too for me. I'm using OSMC though, which uses Kodi 17.6

EDIT: Tested with `18.0-Leia_beta1` too, also working fine. :)

**Comment by jaynford** [comment]
It must be a Kodi 18 thing.

**Comment by jaynford** [comment]
Tried it after a reboot and update, and addons are working. Thanks!
